http:
  port: 8080

apiEndpoints:
  my-api:
    host: localhost
    paths: /api/*

serviceEndpoints:
  express-service:
    url: http://localhost:3000 

policies:
  - cors
  - proxy
  - logs

pipelines:
  default:
    apiEndpoints:
      - my-api
    policies:
      - cors:
          - action:
              origin: "*"            # Allow all origins
              methods:               # Allowed HTTP methods
                - GET
                - POST
                - PUT
                - DELETE
              headers:               # Allowed headers
                - Authorization
                - Content-Type
              credentials: true   
      - logs:
          - action:
            level: info
            logger:
            type: console
            format: '{{timestamp}} [{{level}}] {{message}}'
            timestamp: true # Allow cookies and credentials
      - proxy:
          - action:
              serviceEndpoint: express-service # Forwards requests to the backend