http:
  port: 8080

apiEndpoints:
  my-api:
    host: localhost
    paths: /*

serviceEndpoints:
  express-service:
    url: http://localhost:5001 

policies:
  - cors
  - proxy
  - log
  # - custom-plugin

pipelines:
  default:
    apiEndpoints:
      - my-api
    policies:
      # - custom-plugin:
      - log:
          - action:
              level: info
              message: ${req.method} ${req.originalUrl} # parameter for log action
              logger:
                type: console
                format: '{{timestamp}} [{{level}}] {{message}}'
                timestamp: true
      - cors:
          - action:
              origin: "*"            # Allow all origins
              methods:               # Allowed HTTP methods
                - GET
                - POST
                - PUT
                - DELETE
              headers:               # Allowed headers
                - Authorization
                - Content-Type
              credentials: true   
      - proxy:
          - action:
              serviceEndpoint: express-service # Forwards requests to the backend
      